### ISSUE TITLE
登录和查询插件加载异常 跳过

### ISSUE THREAD

**Issue by ling157** [fjwpsyb/Bncr_plugin#2]
查询.js 插件加载异常 跳过
- Error [ERR_REQUIRE_ESM]: require() of ES Module /bncr/BncrData/node_modules/got/dist/source/index.js from /bncr/BncrData/plugins/自用插件/mod/h5st.js not supported.
Instead change the require of index.js in /bncr/BncrData/plugins/自用插件/mod/h5st.js to a dynamic import() which is available in all CommonJS modules.
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/bncr/BncrData/plugins/自用插件/mod/h5st.js:21:13)
    at Module._0x2c7c58 (evalmachine.<anonymous>:1:3714032)
    at Module._compile (evalmachine.<anonymous>:1:3714191)
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/bncr/BncrData/plugins/自用插件/mod/Doraemon_tool.js:395:14)
    at Module._0x2c7c58 (evalmachine.<anonymous>:1:3714032)
    at Module._compile (evalmachine.<anonymous>:1:3714191)
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/bncr/BncrData/plugins/自用插件/查询.js:60:23)
    at Module._0x2c7c58 (evalmachine.<anonymous>:1:3714032)
    at Module._compile (evalmachine.<anonymous>:1:3714191)
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at require (/bncr/node_modules/bytenode/lib/index.js:306:23)
    at #loadPlugin_One (evalmachine.<anonymous>:1:3721272)
    at evalmachine.<anonymous>:1:3718520
    at Array.forEach (<anonymous>)
    at evalmachine.<anonymous>:1:3718201
    at Array.forEach (<anonymous>)
    at #loadPlugins (evalmachine.<anonymous>:1:3717881)
    at #_init (evalmachine.<anonymous>:1:3715835)
    at async _0x1f671f.init (evalmachine.<anonymous>:1:3714950)
    at async evalmachine.<anonymous>:1:4100140 {
  code: 'ERR_REQUIRE_ESM'
}
- 登录.js 插件加载异常 跳过
- Error [ERR_REQUIRE_ESM]: require() of ES Module /bncr/BncrData/node_modules/got/dist/source/index.js from /bncr/BncrData/plugins/自用插件/mod/h5st.js not supported.
Instead change the require of index.js in /bncr/BncrData/plugins/自用插件/mod/h5st.js to a dynamic import() which is available in all CommonJS modules.
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/bncr/BncrData/plugins/自用插件/mod/h5st.js:21:13)
    at Module._0x2c7c58 (evalmachine.<anonymous>:1:3714032)
    at Module._compile (evalmachine.<anonymous>:1:3714191)
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/bncr/BncrData/plugins/自用插件/mod/Doraemon_tool.js:395:14)
    at Module._0x2c7c58 (evalmachine.<anonymous>:1:3714032)
    at Module._compile (evalmachine.<anonymous>:1:3714191)
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/bncr/BncrData/plugins/自用插件/登录.js:142:23)
    at Module._0x2c7c58 (evalmachine.<anonymous>:1:3714032)
    at Module._compile (evalmachine.<anonymous>:1:3714191)
    at Object..js (/bncr/node_modules/ts-node/dist/index.js:851:20)
    at require (/bncr/node_modules/bytenode/lib/index.js:306:23)
    at #loadPlugin_One (evalmachine.<anonymous>:1:3721272)
    at evalmachine.<anonymous>:1:3718520
    at Array.forEach (<anonymous>)
    at evalmachine.<anonymous>:1:3718201
    at Array.forEach (<anonymous>)
    at #loadPlugins (evalmachine.<anonymous>:1:3717881)
    at #_init (evalmachine.<anonymous>:1:3715835)
    at async _0x1f671f.init (evalmachine.<anonymous>:1:3714950)
    at async evalmachine.<anonymous>:1:4100140 {
  code: 'ERR_REQUIRE_ESM'

**Comment by fjwpsyb** [comment]
需要安装指定的got版本， npm i got@11.8.5

**Comment by ling157** [comment]
> 需要安装指定的got版本， npm i got@11.8.5

可以了谢谢大佬
